version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: devtools-protocol
    versions:
    - 0.0.856957
    - 0.0.858754
    - 0.0.862770
    - 0.0.863986
    - 0.0.868034
    - 0.0.871615
    - 0.0.876073
    - 0.0.876535
  - dependency-name: sinon
    versions:
    - 10.0.1
  - dependency-name: "@babel/parser"
    versions:
    - 7.13.0
    - 7.13.11
    - 7.13.4
    - 7.13.9
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: commander
    versions:
    - 7.2.0
  - dependency-name: "@11ty/eleventy"
    versions:
    - 0.12.1
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.2
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: typescript
    versions:
    - 4.2.2
